import React, { useState } from 'react';
import { Database, Download, Plus, Settings, Trash2, Upload, Users } from 'lucide-react';
import { useStore } from '../context/AppStore.jsx';
import EmployeeForm from '../components/EmployeeForm.jsx';
import EmptyState from '../components/EmptyState.jsx';
import { REPOSITORY_CONTRACT_VERSION, SCHEMA_VERSION } from '../domain/constants.js';

export default function SettingsPage(){const store=useStore();const[editing,setEditing]=useState(null);const[formOpen,setFormOpen]=useState(false);const saveEmployee=(form)=>store.mutate((repo,actor)=>form.id?repo.updateEmployee(form.id,form,actor):repo.createEmployee(form,actor));const removeEmployee=async(row)=>{if(!confirm(`Delete ${row.name}? Existing evaluations will remain for audit history.`))return;await store.mutate((repo,actor)=>repo.deleteEmployee(row.id,actor));};const saveSettings=(patch)=>store.mutate((repo,actor)=>repo.saveSettings(patch,actor));const exportBackup=async()=>{const data=await store.repository.exportBackup();downloadJson(data,`employee-evaluation-backup-${Date.now()}.json`)};const importBackup=async(file)=>{const text=await file.text();const data=JSON.parse(text);if(!confirm('Replace the current local datasets with this backup?'))return;await store.mutate((repo,actor)=>repo.importBackup(data,actor));};return <div className="page-stack"><div className="page-heading"><div><h1>Settings</h1><p>Evaluation cycle, employee master data, and local integration tools</p></div></div><section className="panel"><div className="section-heading"><div><h2>Evaluation Window</h2><p>Control whether supervisors can create and submit evaluations.</p></div><span className={`window-badge ${store.settings.evaluationWindow.toLowerCase().replace(' ','-')}`}>{store.settings.evaluationWindow}</span></div><div className="settings-grid"><label>Active Period<input value={store.settings.activePeriod} onChange={e=>saveSettings({activePeriod:e.target.value})}/></label><label>Open Date<input type="date" value={store.settings.windowOpenDate?.slice?.(0,10)||''} onChange={e=>saveSettings({windowOpenDate:e.target.value?new Date(`${e.target.value}T00:00:00`).toISOString():null})}/></label><label>Close Date<input type="date" value={store.settings.windowCloseDate?.slice?.(0,10)||''} onChange={e=>saveSettings({windowCloseDate:e.target.value?new Date(`${e.target.value}T23:59:59`).toISOString():null})}/></label><label>Grace Period Days<input type="number" min="0" value={store.settings.gracePeriodDays} onChange={e=>saveSettings({gracePeriodDays:Number(e.target.value)||0})}/></label></div><div className="button-row"><button className="btn primary" onClick={()=>saveSettings({evaluationWindow:'Open'})}>Open Window</button><button className="btn secondary" onClick={()=>saveSettings({evaluationWindow:'Grace Period'})}>Grace Period</button><button className="btn danger" onClick={()=>saveSettings({evaluationWindow:'Closed'})}>Close Window</button></div></section>
<section className="panel"><div className="section-heading"><div><h2>Employee Master Data</h2><p>Standalone local source replacing the Monday board employee dataset.</p></div><button className="btn primary" onClick={()=>{setEditing(null);setFormOpen(true)}}><Plus size={16}/> Add Employee</button></div>{!store.employees.length?<EmptyState icon={Users} title="No employees configured" description="Add employees to begin evaluating performance."/>:<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Code</th><th>Department</th><th>Role</th><th>Active</th><th/></tr></thead><tbody>{store.employees.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.email}</small></td><td>{row.employeeCode}</td><td>{row.department||'—'}</td><td>{row.role}</td><td>{row.active!==false?'Yes':'No'}</td><td><div className="row-actions"><button className="icon-button" onClick={()=>{setEditing(row);setFormOpen(true)}} aria-label="Edit">✎</button><button className="icon-button danger-text" onClick={()=>removeEmployee(row)} aria-label="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</section>
<section className="panel"><div className="section-heading"><div><h2>Data & Integration Tools</h2><p>Local provider utilities for development and Supabase handoff.</p></div><Database size={20}/></div><div className="diagnostic-grid"><div><span>Provider</span><strong>{store.health?.provider||'—'}</strong></div><div><span>Writable</span><strong>{store.health?.writable?'Yes':'No'}</strong></div><div><span>Repository Contract</span><strong>v{REPOSITORY_CONTRACT_VERSION}</strong></div><div><span>Schema</span><strong>v{SCHEMA_VERSION}</strong></div></div><div className="button-row"><button className="btn secondary" onClick={exportBackup}><Download size={16}/> Export Backup</button><label className="btn secondary file-button"><Upload size={16}/> Import Backup<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importBackup(e.target.files[0])}/></label><button className="btn secondary" onClick={store.refresh}>Refresh Provider</button></div></section><EmployeeForm open={formOpen} employee={editing} employees={store.employees} onClose={()=>setFormOpen(false)} onSave={saveEmployee}/></div>}
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
